site_name: seajoshc/go
extra:
  homepage: https://github.com/seajoshc/go
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/seajoshc
plugins:
  - search
theme:
  name: material
  icon:
    logo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: blue grey
    accent: teal
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand